name: MCDataLink
version: '${project.version}'
main: org.tobias.mcdatalink.MCDataLink
api-version: '1.13'
authors: [Tobias Auer]
description: Connects the server to MCConnect and provides the in-game stats
website: mc.tobisit.de
